'use client';

import './globals.css';
import 'antd/dist/reset.css';
import { ThemeProvider } from 'next-themes';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import TanstackProvider from '../libs/TanstackProvider';
import ReduxProvider from '../libs/ReduxProvider';
import '@ant-design/v5-patch-for-react-19';
import { StyleProvider } from '@ant-design/cssinjs';

import { Montserrat } from 'next/font/google';
import Header from '@/components/layout/Header';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-montserrat',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <TanstackProvider>
              <AntdRegistry>
                <ConfigProvider
                  theme={{
                    token: {
                      fontFamily: montserrat.style.fontFamily,
                    },
                  }}
                >
                  <StyleProvider hashPriority="low">{children}</StyleProvider>
                </ConfigProvider>
              </AntdRegistry>
            </TanstackProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
